### ISSUE TITLE
How to update multiple records at one?

### ISSUE THREAD

**Issue by ayashjorden** [fog/fog-dynect#10]
Hi,
I'm trying to understand how, for example, to update multiple A records' TTL in one save/publish/other operation.

Thank you,
Yarden

**Comment by ayashjorden** [comment]
Hi @geemus,
I've recently integrated this gem into [puppetlabs-dns](https://github.com/puppetlabs/puppetlabs-dns/pull/7) module.

It works very nice, but some functionality is still missing.
How can this be achieved? is there a `put_multiple_records` I'm missing somewhere?

Thank you,
Yarden

**Comment by plribeiro3000** [comment]
Hello @ayashjorden. Currently there is only [`put_record`](https://github.com/fog/fog-dynect/blob/master/lib/fog/dynect/requests/dns/put_record.rb) available.

Is `put_multiple_records` something dynect supports or do we have to do it ourselves?

**Comment by ayashjorden** [comment]
Dynect has an API that supports multiple records, [here](https://help.dyn.com/replace-a-records-api/).
If I understand correctly, we need to use an array of records a the payload of the PUT request to that API.

To give some background, I encountered this operation while I was trying to update multiple records, hitting `record.save` on the first one, trying to `save` the following records resulted in errors of: record not up to date.

**Comment by ayashjorden** [comment]
While we're at it, appreciate to keep in mind a related issue #11 .

Thank you,
Yarden

**Comment by plribeiro3000** [comment]
Hmm. Thanks for the link.

I believe we need to patch it to add the new request and add the extra parameters to fix #11.

As of now i'm not able to code so perhaps you might want to help?

**Comment by ayashjorden** [comment]
Sure :)
1. In order to fix the TTL issue, aside from adding `:ttl      => record['ttl']`, what/where else I need to patch?
2. `put_multiple_records` will be a new file requests/dns/put_multiple_records.rb ?
3. In `record.save` we execute `zone.publish` which may/may-not change record IDs in DynECT. can this be removed and let the user decide when to publish a zone?

Any other tips/comments are welcome,
Yarden

**Comment by ayashjorden** [comment]
Technical issue:
How do I  make the `irb` util require the fog-dynect gem from the local directory so I can debug it ?

**Comment by plribeiro3000** [comment]
I believe you might be able to do `bundle console` to enter debug mode.

**Comment by plribeiro3000** [comment]
Answering:
1 - It should be a new attribute at the model using `Fog`'s DSL and then using it when needed
2 - Yes
3 - Depends on how it works. I'm not a dynect expert so you need to work with me on this.
Whats the intention on `zone.publish` that make it necessary when saving a record?

**Comment by ayashjorden** [comment]
1. It's already in the model `lib/fog/dynect/models/dns/record.rb`
2. ACK
3. We should ask @geemus about [this](https://github.com/fog/fog-dynect/blob/master/lib/fog/dynect/models/dns/record.rb#L39).

I'll try to work on this later this week.

**Comment by plribeiro3000** [comment]
👍

**Comment by ayashjorden** [comment]
Hi @plribeiro3000,
I've created a #12 for fixing the TTL issue.

Regarding saving multiple records, DynECT API behaviour is that for certain record ('some.record.domain.com'), the TTL is the same. so when hitting `record.save` it applies the TTL to all records on the same node (e.g. some.record.domain.com).
So, we should leave the `zone.publish` call as is for now. I'll implement a fix in puppetlabs-dns module.
