### ISSUE TITLE
TLL is missing when retreiving zone or records

### ISSUE THREAD

**Issue by ayashjorden** [fog/fog-dynect#11]
Hi @geemus,
Sorry for hammering you, please point me to the right person if needed.

I've read the code and tried to patch the gem to populate the TTL field of retrieved records, but no success to do so.

I saw a `get_record` request but there's a comment in [records.rb](https://github.com/fog/fog-dynect/blob/master/lib/fog/dynect/models/dns/records.rb#L32) that some arguments are missing at that location.

Thought about adding an options argument that will hold the record type and fqdn but that would be the opposite of the `options` argument in `get_record` method(in dynect/requests/dns/get_record.rb)

Can you throw a tip or two on how to get the TTL field populated?

**Comment by geemus** [comment]
Hmm, I'm not sure. It appears that the get_record method simply JSON parses the response it gets, which would lead me to believe that the response doesn't contain the TTL (and barring that, I'm not sure where to go get that value from). Perhaps it requires a separate request to find? If that is the case, we could perhaps set it up as a lazy-load attribute to pull that value just when asked for? I'm not familiar with dynect specifics, so would appreciate your insight and help.

**Comment by ayashjorden** [comment]
@geemus please take a look at #12, this is all that was needed to get the TTL.

**Comment by geemus** [comment]
Ah, got it. I was under the impression there was more to be done from above. Thanks for clarifying.
