### ISSUE TITLE
Job is still incomplete

### ISSUE THREAD

**Issue by snowsky** [fog/fog-dynect#4]
I have got too many records in the zone, so it printed out the below message. Is there a way to paginate the output or with cursor?

```
/usr/local/lib/ruby/gems/2.2.0/gems/fog-dynect-0.0.2/lib/fog/dynect/dns.rb:144:in `rescue in poll_job': Job 2094586824 is still incomplete (Fog::DNS::Dynect::JobIncomplete)
    from /usr/local/lib/ruby/gems/2.2.0/gems/fog-dynect-0.0.2/lib/fog/dynect/dns.rb:131:in `poll_job'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fog-dynect-0.0.2/lib/fog/dynect/dns.rb:105:in `request'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fog-dynect-0.0.2/lib/fog/dynect/requests/dns/get_all_records.rb:14:in `get_all_records'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fog-dynect-0.0.2/lib/fog/dynect/models/dns/records.rb:14:in `all'
    from tpn_dns.rb:39:in `<main>'
```

**Comment by glennpratt** [comment]
It polls, but is hitting a timeout never the less.

https://github.com/fog/fog-dynect/blob/master/lib/fog/dynect/dns.rb#L128-L151

I'm not sure about pagination, have any information about that?

Related information:
60a4bc07829cddc1ffa2f124f01fa476d5cc9f08
https://github.com/Netflix/denominator/issues/261

**Comment by snowsky** [comment]
resolved this issue by setting up a longer time_to_wait value.
