### ISSUE TITLE
CHANGELOG.md is out of date

### ISSUE THREAD

**Issue by dcarral** [fog/fog-dynect#5]
While the gem has been recently updated to _v0.0.3_ ([with this commit](https://github.com/fog/fog-dynect/commit/b08eb45f3c79423bfd39e3260f07556a873fbabb)), the [changelog](https://github.com/fog/fog-dynect/blob/master/CHANGELOG.md) just includes _v0.0.1_ (initial extraction from `fog`)

**Comment by blkperl** [comment]
@geemus since you released the new versions any chance you can update the changelog?
